# Build the staging env app on EAS Cloud service.
name: 'Build | Staging'
run-name: Build | Staging for ${{ inputs.platform }} on ${{ github.ref_name }}
on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: Which platform to build for
        options:
          - ios
          - android
          - all
        required: true
      email:
        type: choice
        description: Do you want to notify the client via email?
        options:
          - yes
          - no
        default: no
jobs:
  use-common-config:
    name: 'Build (staging / ${{ github.event.inputs.platform }})'
    uses: ./.github/workflows/common-config.yml
    secrets: inherit
    with:
      platform: ${{ github.event.inputs.platform }}
      email: ${{ github.event.inputs.email }}
      environment: stag
