# Build the staging env app on EAS Cloud service.
name: 'Build | Staging'
on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: Which platform to build for
        options:
          - ios
          - android
        required: true
jobs:
  build:
    name: 'Build (staging / ${{ github.event.inputs.platform }})'
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Setup repo
        uses: actions/checkout@v3

      - name: ⎔ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: ./package.json

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🌎 Compile translations
        run: npm run i18n:extract && npm run i18n:compile

      - name: 🚀 Build app
        id: build-app
        run: |
          eas build --platform ${{ inputs.platform }} --profile stag --non-interactive | tee temp.txt
          echo "BUILD_URL=$(echo "$(cat temp.txt)" | grep -o 'Build details: [^ ]*' | awk '{print $3}')" >> $GITHUB_OUTPUT

      - name: ✅ Notify slack success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: builds
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: ${{ github.event.organization.avatar_url }}
          SLACK_TITLE: 'Build successfull for ${{ inputs.platform }} :white_check_mark:'
          SLACK_MESSAGE: 'See <${{ steps.build-app.outputs.BUILD_URL }}|EAS build> :rocket:'
          SLACK_USERNAME: ${{ github.event.repository.name }} - ${{ github.workflow }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: ❌ Notify slack fail
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: builds
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: ${{ github.event.organization.avatar_url }}
          SLACK_TITLE: 'Build failed for ${{ inputs.platform }} :x:'
          SLACK_MESSAGE: 'See <${{ steps.build-app.outputs.BUILD_URL }}|EAS build> for more info :sad_pepe:'
          SLACK_USERNAME: ${{ github.event.repository.name }} - ${{ github.workflow }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
