# Build the dev env app on EAS Cloud service.
name: 'Build | Dev'
run-name: Build | Dev (for ${{ inputs.platform }} on ${{ github.ref_name }})
on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: Which platform to build for
        options: [ios, android, all]
        required: true
        default: all
      email:
        type: choice
        description: Notify the client via email?
        options: ['false', 'true']
        default: 'false'

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    outputs:
      BUILD_URL: ${{ steps.build.outputs.BUILD_URL }}
    steps:
      - name: ⬇️ Setup repo
        uses: actions/checkout@v4

      - name: 🚀 Build
        id: build
        uses: ./.github/actions/build-app
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          platform: ${{ inputs.platform }}
          environment: development

  slack:
    name: Notify Slack
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: ⬇️ Setup repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/notify-slack
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          BUILD_URL: ${{ needs.build.outputs.BUILD_URL }}
          platform: ${{ inputs.platform }}
          status: ${{ needs.build.result }}

  email:
    name: Notify Clients
    needs: build
    if: ${{ needs.build.result == 'success' && inputs.email == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Setup repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/notify-clients
        with:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_GITHUB_ACTION_API_KEY }}
          BUILD_URL: ${{ needs.build.outputs.BUILD_URL }}
          platform: ${{ inputs.platform }}
          environment: development
