name: 'Verify'
on:
  push:
    branches: [dev, test, stag, prod]
  pull_request:
    branches: [dev]
jobs:
  build:
    name: 'Lint, typecheck, and test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run typecheck

      - name: Check formatting
        run: npm run format:check

      # Conditional step for checking translations
      - name: Check translations
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/prod" || "${{ github.ref }}" == "refs/heads/stag" ]]; then
            npm run i18n:compile:strict
          else
            npm run i18n:compile
          fi

      - name: Lint code
        run: npm run lint

      - name: Run test suite
        run: npm test

      - name: Notify slack on fail
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: builds # TODO: project channel name
          status: FAILED
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
