name: 'Verify'
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  build:
    name: 'Lint, typecheck, and test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run typecheck

      - name: Check formatting
        run: npm run format:check

      - name: Lint code
        run: npm run lint

      - name: Run test suite
        run: npm test
